CREATE TABLE IF NOT EXISTS "AppropriationBills" 
(
	"AppropriationBillId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"BFY" TEXT NOT NULL DEFAULT NS,
	"Title"	TEXT NOT NULL DEFAULT NS,
	"PublicLaw"	TEXT NOT NULL DEFAULT NS,
	"EnactedDate"	TEXT NOT NULL DEFAULT NS
);
