CREATE TABLE IF NOT EXISTS "Accounts" 
(
	"AccountId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Code"	TEXT NOT NULL,
	"Name"	TEXT NOT NULL DEFAULT 'NS',
	"Title"	TEXT NOT NULL DEFAULT 'NS',
	"ProgramAreaCode" TEXT NOT NULL DEFAULT 'NS',
	"ActivityCode"	TEXT NOT NULL DEFAULT 'NS',
	"GoalCode"	TEXT NOT NULL DEFAULT 'NS',
	"ObjectiveCode"	TEXT NOT NULL DEFAULT 'NS',
	"NpmCode" TEXT NOT NULL DEFAULT 'NS',
	"ProgramProjectCode" TEXT NOT NULL DEFAULT 'NS'
);
