CREATE TABLE IF NOT EXISTS "Employees" 
(
	"EmployeeId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"FirstName"	TEXT NOT NULL DEFAULT NS,
	"LastName"	TEXT NOT NULL DEFAULT NS,
	"Section"	TEXT NOT NULL DEFAULT NS,
	"Email"	TEXT NOT NULL DEFAULT NS,
	"Office" TEXT NOT NULL DEFAULT NS,
	"PhoneNumber"	TEXT NOT NULL DEFAULT NS,
	"CellNumber" TEXT NOT NULL DEFAULT NS,
	"Status"	TEXT NOT NULL DEFAULT NS
);
