CREATE TABLE "FullTimeUtilization" 
(
	"FullTimeUtilizationId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"BudgetLevel"	INTEGER NOT NULL DEFAULT 7,
	"RpioCode"	TEXT NOT NULL DEFAULT 06,
	"BFY"	TEXT NOT NULL DEFAULT 'NS',
	"FundCode"	TEXT NOT NULL DEFAULT 'NS',
	"NpmCode"	TEXT NOT NULL DEFAULT 'NS',
	"AhCode"	TEXT NOT NULL DEFAULT 'NS',
	"OrgCode"	TEXT NOT NULL DEFAULT 'NS',
	"RcCode"	TEXT NOT NULL DEFAULT 'NS',
	"AccountCode"	TEXT NOT NULL DEFAULT 'NS',
	"ProgramProjectCode"	TEXT NOT NULL DEFAULT 'NS',
	"ProgramAreaCode"	TEXT NOT NULL DEFAULT 'NS',
	"Allocation"	REAL DEFAULT 0.0,
	"Expended"	REAL DEFAULT 0.0,
	"Available"	REAL DEFAULT 0.0
);