CREATE TABLE IF NOT EXISTS "Funds" 
(
	"FundId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Code"	TEXT NOT NULL,
	"Name"	TEXT NOT NULL DEFAULT NS,
	"TreasurySymbol" TEXT NOT NULL DEFAULT NS,
	"Title"	TEXT NOT NULL DEFAULT NS
);
