CREATE TABLE IF NOT EXISTS "Outlays" 
(
	"OutlayId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"BudgetLevel"	TEXT NOT NULL DEFAULT NS,
	"RpioCode"	TEXT NOT NULL DEFAULT NS,
	"BFY"	TEXT NOT NULL DEFAULT NS,
	"FundCode"	TEXT NOT NULL DEFAULT NS,
	"AhCode"	TEXT NOT NULL DEFAULT NS,
	"OrgCode"	TEXT NOT NULL DEFAULT NS,
	"RcCode"	TEXT NOT NULL DEFAULT NS,
	"AccountCode"	TEXT NOT NULL DEFAULT NS,
	"BocCode"	TEXT NOT NULL DEFAULT NS,
	"Commitments"	NUMERIC NOT NULL DEFAULT 0.0,
	"OpenCommitments"	NUMERIC NOT NULL DEFAULT 0.0,
	"Obligations"	NUMERIC NOT NULL DEFAULT 0.0,
	"ULO"	NUMERIC NOT NULL DEFAULT 0.0,
	"Balance"	NUMERIC NOT NULL DEFAULT 0.0,
	"NpmCode"	TEXT NOT NULL DEFAULT NS,
	"ProgramProjectCode"	TEXT NOT NULL DEFAULT NS,
	"ProgramAreaCode"	TEXT NOT NULL DEFAULT NS
);
