
CREATE TABLE IF NOT EXISTS "ControlNumbers" (
	"ControlNumberId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"BFY"	TEXT NOT NULL DEFAULT NS,
	"RPIO"	TEXT NOT NULL DEFAULT 06,
	"AhCode"	TEXT DEFAULT 06,
	"RegionControlNumber"	INTEGER NOT NULL DEFAULT 0,
	"FundCode"	TEXT NOT NULL DEFAULT NS,
	"FundControlNumber"	INTEGER NOT NULL DEFAULT 0,
	"RcCode"	TEXT NOT NULL DEFAULT NS,
	"DivisionName"	TEXT NOT NULL DEFAULT NS,
	"DivisionControlNumber"	INTEGER NOT NULL DEFAULT 0,
	"DateIssued"	TEXT NOT NULL DEFAULT NS
);
